dbt_project.yml

Adds version support for dbt 0.19

Adding support for dbt 0.19

---

dbt_project.yml
macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql

Fix between logic and switch to expression_between macro

---

integration_tests/models/schema_tests/schema.yml

Increases recency test interval on timeseries_hourly_data_extended

---

macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql

Fixes set logic in expect_column_distinct_values_to_be_in_set

---

README.md
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal_other_table.sql

Add expect_column_distinct_count_to_equal_other_table

---

integration_tests/models/schema_tests/schema.yml
integration_tests/models/schema_tests/timeseries_data.sql
integration_tests/models/schema_tests/timeseries_data_extended.sql
integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql

- Changes row values to floats
- Fixes hourly data test which incorrectly took logs

Fixes timeseries integration tests

---

CHANGELOG.md
README.md
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/_generalized/expression_between.sql
macros/schema_tests/aggregate_functions/expect_column_max_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_median_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_min_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_proportion_of_unique_values_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_quantile_values_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_stdev_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_sum_to_be_between.sql
macros/schema_tests/aggregate_functions/expect_column_unique_value_count_to_be_between.sql
macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql
macros/schema_tests/string_matching/expect_column_value_lengths_to_be_between.sql
macros/schema_tests/table_shape/expect_table_column_count_to_be_between.sql
macros/schema_tests/table_shape/expect_table_row_count_to_be_between.sql

This PR will add a CHANGELOG starting with the `0.3.4` release.

Adding a CHANGELOG

---

macros/schema_tests/_generalized/expression_is_true.sql
macros/schema_tests/aggregate_functions/expect_column_most_common_value_to_be_in_set.sql
macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
macros/schema_tests/table_shape/expect_table_row_count_to_equal.sql

dispactching `expect_table_row_count_to_equal` to create a shim to make it compatible with TSQL

dispactching expect_table_row_count_to_equal

---

macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql
macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_contain_set.sql
macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql
macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql
macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql

because https://twitter.com/emilyhawkins__/status/1400967270537564160

Fix join syntax

---

macros/math/rand.sql

Adds support for Redshift random function (per @ahmedrad)

Add support for Redshift random function

---

CHANGELOG.md
dbt_project.yml

Add support for dbt 0.21

---

.gitignore
CHANGELOG.md
README.md
dbt_project.yml
integration_tests/dbt_project.yml
integration_tests/models/schema_tests/schema.yml
integration_tests/test.sh
packages.yml

Updates the following files to support dbt==0.1.x
* .gitignore
* dbt_project.yml
* integration_tests/dbt_project.yml

Upgrade project to support dbt 0.1.x

---

macros/schema_tests/_generalized/equal_expression.sql
macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal_other_table.sql
macros/schema_tests/multi-column/expect_multicolumn_sum_to_equal.sql
macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql

Couple of small cleanups of dead parameters.

Repo cleanup 2022/1

---

README.md
integration_tests/models/schema_tests/schema.yml

Add example for dynamic date params in expect_row_values_to_have_data_for_every_n_datepart

---

integration_tests/models/schema_tests/schema.yml
macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql

Fix take_diff syntax in moving stddev test

---

integration_tests/models/schema_tests/schema.yml
integration_tests/models/schema_tests/timeseries_data_grouped.sql
macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql

Fix timestamp comparisons in expect_grouped_row_values_to_have_recent_data

---

README.md

fix name of the macro in the documentation

---

README.md

Hey @clausherther,
I'm adding which adds re_data to featured sponsors as mentioned on Github.
Let me know if all is good here! :)

Add re_data to sponsors :)

---

macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql

- Removes dangling dbt-utils reference

Remove dangling dbt-utils reference

---

.circleci/config.yml
README.md
dbt_project.yml
integration_tests/dbt_project.yml
integration_tests/models/schema_tests/data_test_factored.sql
integration_tests/models/schema_tests/series_10.sql
integration_tests/models/schema_tests/series_4.sql
integration_tests/models/schema_tests/timeseries_data.sql
integration_tests/models/schema_tests/timeseries_hourly.sql
macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql
macros/schema_tests/distributional/expect_column_values_to_be_within_n_stdevs.sql
macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
macros/utils/groupby.sql
packages.yml

Remove references to dbt_utils

---

README.md
integration_tests/models/schema_tests/data_test_factored.sql
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/table_shape/expect_table_row_count_to_be_between.sql
macros/schema_tests/table_shape/expect_table_row_count_to_equal.sql
macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql
macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table_times_factor.sql

Adds group by to expect_table_row_count_to_equal_other_table

---

README.md

Add Datacoves sponsor

---

macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql

Closes #299
Adds md5 around column in `unpivoted_columns`.
This will allow for different data types to be used within the test.
@clausherther

Update Test Expecting Select Column Values To Be Unique Within Record

---

.circleci/config.yml
integration_tests/ci/profiles.yml

Upgrades CI to dbt==1.7.x and fixes Spark config to work with 1.7.x.

[CI] Uprade to dbt=1.7.x

---

.circleci/config.yml
integration_tests/ci/profiles.yml
integration_tests/dbt_project.yml
integration_tests/models/schema_tests/schema.yml

This PR updates the CI configs to support dbt 1.8.x.
@clausherther

Upgrade for dbt 1.8.x
