README.md, integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_data_extended.sql, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_greater_than.sql, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal.sql
Adds `expect_column_distinct_count_to_equal` and `expect_column_distinct_count_to_be_greater_than` to allow testing for a defined number of unique values in a column. 
For example, this could be used to check for the unique number of `batch_id` values in a given day (filtered via `row_condition`).
```
- name: my_fact_table
columns:
- name: batch_id
tests:
- dbt_expectations.expect_column_distinct_count_to_equal:
row_condition: date_day = {{ dbt_date.yesterday() }}
value: 24
```
```
- name: my_fact_table
columns:
- name: batch_id
tests:
- dbt_expectations.expect_column_distinct_count_to_be_greater_than:
row_condition: date_day = {{ dbt_date.yesterday() }}
value: 12
```
=> Adds expect_column_distinct_count_** tests

macros/schema_tests/column_values_basic/expect_column_values_to_be_unique.sql, macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
Makes SQL output for multi-column uniqueness checks a little more readable by forgoing the surrogate key construction.
=> Refactor single & multi-column uniqueness tests

integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql
This refactor would allow users to specify a period other than 'day' for their timeseries tests.
This is a **breaking change** as the macro renames to following parameters:
- `group_by` --> `date_column_name`
- `lookback_days` --> `lookback_periods`
- `trend_days` --> `trend_periods`
- `test_days` --> `test_periods`
=> Refactor expect_column_values_to_be_within_n_moving_stdevs

macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_of_type.sql
Refactors `expect_column_values_to_be_of_type` and `expect_column_values_to_be_in_type_list` to use `Column.dtype` instead of `data_type` to make type comparisons easier.
Fixes #22
=> Refactor column type checks to use dtype

macros/schema_tests/_generalized/equal_expression.sql, macros/schema_tests/_generalized/expression_is_true.sql, macros/schema_tests/aggregate_functions/expect_column_most_common_value_to_be_in_set.sql, macros/schema_tests/aggregate_functions/expect_column_stdev_to_be_between.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_stdevs.sql, macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql, macros/schema_tests/table_shape/expect_table_column_count_to_be_between.sql
Hi!
I have been working on a package to port this package to T-SQL. 
Some of the macros require the `adapter.dispatch` call for me to able to override the default version.
If those changes are accepted I should be able to release `dbt-expectations-tsql` shortly.
Cheers,
=> Modifications for tsql support

integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql
This PR fixes the integration tests for `timeseries_data_extended` and `timeseries_hourly_data_extended`by using the `generates_series` macro from dbt_utils.
It also disables the `expect_column_values_to_be_of_type` test for `timeseries_hourly_data_extended.date_hour` until I can figure out how to pass in platform-specific values for `column_type`.
Closes #24
=> Fixes datetime series for Snowflake

README.md, integration_tests/models/schema_tests/data_test_factored.sql, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table _times_factor.sql
Hi
We have a use case where we have a table a and we want to validate that table b always has a row count that is equal to the row count in table a times a predefined factor.
=> Add expect_table_column_count_to_equal_other_table_times_factor

integration_tests/dbt_project.yml, integration_tests/macros/datatypes.sql, integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql, macros/math/rand.sql, macros/regex/regexp_instr.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/utils/datatypes.sql
This PR closes #39 and #38 by adding initial support to better handle datetime and timestamp types and also add support for the equivalent of `regexp_instr` for Postgres.
=> Add initial Postgres support

integration_tests/models/schema_tests/schema.yml, macros/schema_tests/_generalized/equal_expression.sql, macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table _times_factor.sql, macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql
=> Adds better support for integer division issue in equal_expression macro  

integration_tests/models/schema_tests/schema.yml, macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table _times_factor.sql, macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql
Closes #42 
Also refactors `expect_table_row_count_to_equal_other_table_times_factor` to just use `expect_table_row_count_to_equal_other_table` with a `factor` parameter (cc: @nysthee)
=> Adds ability to set row_condition on row_count tests

README.md, integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_data_grouped.sql, macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
Closes #47 
Usage:
```yaml
- name : timeseries_data_grouped
tests :
- dbt_expectations.expect_grouped_row_values_to_have_recent_data:
group_by: [group_id]
timestamp_column: date_day
datepart: day
interval: 1
- dbt_expectations.expect_grouped_row_values_to_have_recent_data:
group_by: [group_id, row_value]
timestamp_column: date_day
datepart: day
interval: 1
```
=> Add test "expect_grouped_row_values_to_have_recent_data"

integration_tests/models/schema_tests/series_10.sql, integration_tests/models/schema_tests/series_4.sql, integration_tests/models/schema_tests/timeseries_base.sql, integration_tests/models/schema_tests/timeseries_data.sql, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_data_grouped.sql, integration_tests/models/schema_tests/timeseries_hourly.sql, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql
I'm working on making a shim package for dbt-expectations inside of tsql-utils (https://github.com/dbt-msft/tsql-utils/pull/38).
TSQL doesn't  support nested CTEs, the solution is to break calls to `dbt_utils.date_spine()` out to their own models that are referenced in the first CTE of the downstream model.
I tested these changes and the models at least run, I don't expect any tests to fail.
=> make integration tests TSQL compatible

README.md, macros/schema_tests/_generalized/equal_expression.sql
Initial take on making `get_select` in `equal_expression` more explicit. 
Closes #62
=> Refactor get_select() to make grouping more explicit

README.md, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/_generalized/expression_between.sql, macros/schema_tests/aggregate_functions/expect_column_max_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_median_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_min_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_proportion_of_unique_values_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_quantile_values_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_stdev_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_sum_to_be_between.sql, macros/schema_tests/aggregate_functions/expect_column_unique_value_count_to_be_between.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql, macros/schema_tests/string_matching/expect_column_value_lengths_to_be_between.sql, macros/schema_tests/table_shape/expect_table_column_count_to_be_between.sql, macros/schema_tests/table_shape/expect_table_row_count_to_be_between.sql
This adds support for optional min/max values to most `between` type tests:
e.g.:
```yaml
- dbt_expectations.expect_column_values_to_be_between:
min_value: 0
```
Would essentially translate to `>=0`
=> Add support for optional min/max to between tests

README.md, integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_base.sql, integration_tests/models/schema_tests/timeseries_data.sql, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_data_grouped.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql, macros/utils/datatypes.sql, packages.yml
This adds a new macro, `expect_row_values_to_have_data_for_every_n_datepart`, which tests whether a model has values for every grouped `date_part`.
For example, this tests whether a model has data for every `day` (grouped on `date_col`) from either a specified `start_date` and `end_date`, or for the `min`/`max` value of the specified `date_col`.
```yaml
tests:
- dbt_expectations.expect_row_values_to_have_data_for_every_n_datepart:
date_col: date_day
date_part: day
```
=> Add new date frequency test: expect_row_values_to_have_data_for_every_n_datepart

README.md
Updated the descriptions for the column type check so it is more clear that they check the data type of the column, not the values within it.
=> Update description of type check tests

integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/schema.yml, macros/math/rand.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql
This is a fix for this bug: https://github.com/calogica/dbt-expectations/issues/90
=> Fix value in set validation

CHANGELOG.md, macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql
This hopefully fixes #98  and #99 
* For #98 this remove `''` that were inadvertently added during an earlier PR
* For #99 this explicitly casts the list of columns to a platform specific string type
=> Fix types in expect_table_columns_to_match_* tests 

macros/regex/regexp_instr.sql
with the change to adapter resolution in dbt 0.20, redshift has been
using the postgres version of the macro, which fails because the
function `regexp_matches` exists on Postgres but not Redshift. While the
`regexp_instr` does exist on Redshift, so the default was correct all
along.
This commit simply adds an explicit adapter for Redshift that is the
same as the default adapter.
This should fix #97
=> Fix regexp_instr on Redshift

README.md, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql, macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql
This PR add the possibility to apply conditions (`row_condition`) to `expect_grouped_row_values_to_have_recent_data` test
=> [Feature] Add row_condition on expect_grouped_row_values_to_have_recent_data test

macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_equal_set.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql
Converts set logic to SQL joins in the following tests:
- expect_column_distinct_values_to_equal_set
- expect_column_values_to_be_in_type_list
- expect_table_columns_to_contain_set
- expect_table_columns_to_match_ordered_list
- expect_table_columns_to_match_set
Closes #100
=> Convert set logic to SQL joins

CHANGELOG.md, macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql
=> expect_table_columns_to_match_ordered_list: refactor row_number to use loop.index

README.md
[Resolves issue 120](https://github.com/calogica/dbt-expectations/issues/120) adding `expect_table_columns_to_contain_set`example.
=> Add expect_table_columns_to_contain_set to README

macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql
The `expect_table_columns_to_match_ordered_list` macro is using column
names as direct strings, which doesn't work on Redshift without an
explicit cast to string.
This cast was added previously and removed again in
https://github.com/calogica/dbt-expectations/commit/c698a1a1108435c18cc7680885795aeb47b8fe74#diff-14b201719d47d2b58e18a4896f8cb1d1f0bc3b414694499ef5eb738b683fb955L11-L12
Fixes #122 
I have not tested this, just applied the previous fix.
=> Fix Redshift compatibility

README.md
This PR appends missing optional parameters documentation to the main README file, so that the folks who are new to this dbt package is aware of them. Currently you have to click on the title of of each one to see what they are. Addresses #76 . 
For future:
- This doc is getting to be a pretty long list, so it may be helpful to divide them up for easier maintainability and readability.
- It may be beneficial to look into docs generating library rather than manually editing the README if this package grows significantly.
=> Append missing optional parameters documentation to README.md

macros/schema_tests/string_matching/expect_column_value_lengths_to_equal.sql, macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern.sql, macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern_list.sql, macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql, macros/schema_tests/string_matching/expect_column_values_to_match_regex_list.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern_list.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_regex.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_regex_list.sql
Fix for issue #125.
Problem: All the methods in macros/schema_tests/string_matching/ define a group_by_columns=group_by functionality, but group_by is not defined in the method which makes them fail with 'MacroGenerator' object is not iterable.
Solution: we set group_by = None as it's not used by the method.
=> Fix missing group_by default value in string_matching macros

.gitignore, CHANGELOG.md, dbt_project.yml, integration_tests/dbt_project.yml, integration_tests/models/schema_tests/schema.yml
This is a backwards compatible patch release that updates following files to support dbt 0.1.x
- .gitignore
- dbt_project.yml
- integration_tests/dbt_project.yml
This release will work with versions of versions of dbt-date < 0.5.0 (and in turn versions of dbt-utils < 0.8.0).
cc: @joellabes
=> Patch release to support dbt 0.1.x 

macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql
This PR fixes #130.
**Context**
In some circumstances, Redshift will fail to execute queries generated by `expect_column_values_to_be_in_type_list` if it is unable infer the type of the `relation_column` or `relation_column_type` fields. This commit enforces a casting of those values to a string type to prevent ambiguity.
**Integration Tests (Redshift)**
<details>
<summary>Test Results</summary>
```
$ ./test.sh redshift
18:00:03  Running with dbt=1.0.0
18:00:04  Unable to do partial parsing because config vars, config profile, or config target have changed
18:00:04  Unable to do partial parsing because a project config has changed
18:00:06  Found 11 models, 93 tests, 0 snapshots, 0 analyses, 580 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
18:00:06
18:00:07 …
```
=> Fix `expect_column_values_to_be_in_type_list` for Redshift in 0.5.0

CHANGELOG.md, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql, macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql, macros/schema_tests/multi-column/expect_column_pair_values_to_be_in_set.sql, macros/schema_tests/table_shape/expect_column_to_exist.sql, macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql
This adds better support for Redshift by typing implicit `varchar` fields explicitly to strings.
=> Make string field types more explicit

README.md
The README.md notes that the project only supports dbt 0.21.x, but dot-expectations 0.5.0 and above support 1.0.0.  
Just wanted to quickly change the documentation to minimize confusion.
=> Fix documentation to note DBT 1.0.0 compatibility

macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql
This PR addresses #104 by using timestamps as the comparison to work out older data.
This was driven by experiencing an issue using the test on data using a timestamp as the recency source for data that should be fresher than 6 hours.
The original code was pulling data from the table that had a timestamp <= todays date, meaning that although the most recent data was loaded 15 minutes before, the test was failing.
Tested on Snowflake
Apologies if this doesn't meet the standards for contributions for the repo, but before #139 is implemented, it's justa guess :(
Also please let me know if anything else is required
=> Change check for data date out of range to use timestamp

README.md, integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/emails.sql, integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/window_function_test.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql
Not possible to put partition by parameters in the following tests:
- [expect_column_values_to_be_increasing](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql)
- [expect_column_values_to_be_decreasing](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql)
- Added an optional parameter which allow to partition by. 
- Updated the README.MD with accordingly
Please let me know if there is anything
=> Added partition by in lag tests

integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_data.sql, macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql, macros/utils/datatypes.sql
This PR attempts to fix #104 by converting all evals in the test macro to force a cast to `timestamp`.
=> Fix expect_row_values_to_have_recent_data issues on bigquery

integration_tests/models/schema_tests/schema.yml
Testing `expect_column_values_to_be_within_n_moving_stdevs` can be flakey b/c of the random nature of the test data.
This PR set `severity` to `warn` for any integration tests using `expect_column_values_to_be_within_n_moving_stdevs`.
=> Set flakey tests to severity warn

integration_tests/models/schema_tests/schema.yml, macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
Fixes #170
`ignore_row_if` wasn't properly handled because `row_condition_ext` was set but never used.
=> Fix expect_compound_columns_to_be_unique to properly handle "ignore_row_if"

dbt_project.yml, integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/timeseries_data.sql, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_data_grouped.sql, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql, integration_tests/models/schema_tests/window_function_test.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql, macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql, macros/schema_tests/string_matching/expect_column_value_lengths_to_be_between.sql, macros/schema_tests/string_matching/expect_column_value_lengths_to_equal.sql, macros/schema_tests/table_shape/expect_column_to_exist.sql, macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql, macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql, macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_not_contain_set.sql, packages.yml
Closes #188 
- Removes references to macros now supported in dbt-core.
- Requires dbt-utils 0.9.x
- Requires dbt 1.2.x
=> Migrate to dbt-utils 0.9.0 and dbt-date 0.6.0

README.md, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_less_than.sql
- expect_column_distinct_count_to_be_less_than.sql is a copy of expect_column_distinct_count_to_be_greater_than.sql, but with "<" instead of ">"
- README.md is updated to reflect addition
=> Add expect_column_distinct_count_to_be_less_than.sql

integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
Fixes #200 
This fixes the implementation of the `ignore_row_if` parameter in `expect_compound_columns_to_be_unique` highlighted by @mcannamela in #200 and adds a test to `data_test`.
=> Fix boolean logic in `expect_compound_columns_to_be_unique` `ignore_row_if` 

macros/schema_tests/_generalized/_ignore_row_if_expression.sql, macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql, macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql
Closes #203 
- Refactors `ignore_row_if` into reusable macro
- Updates ignore_row_if logic in `expect_select_column_values_to_be_unique_within_record`
=> Refactor ignore_row_if logic

integration_tests/models/schema_tests/schema.yml, integration_tests/models/schema_tests/timeseries_data.sql, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_data_grouped.sql, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_stdevs.sql, macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
* `expect_grouped_row_values_to_have_recent_data` did not correctly apply grouping levels to grouped recency checks
* Closes #206 
* `expect_column_values_to_be_within_n_stdevs` did not expect a list for the `group_by`, unlike other similar tests
* Closes #194
=> Fix group by logic in grouped recency and stdev tests

README.md, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_greater_than.sql, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_less_than.sql, macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal.sql, macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql, macros/schema_tests/aggregate_functions/expect_column_most_common_value_to_be_in_set.sql
This aligns defaults for `quote_values`. Also, removes the `quote_values` parameter where it wasn't being used.
Closes #229
=> Clean up quote values defaults

integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/timeseries_data.sql, integration_tests/models/schema_tests/timeseries_data_extended.sql, integration_tests/models/schema_tests/timeseries_data_grouped.sql, integration_tests/models/schema_tests/timeseries_hourly_data_extended.sql, integration_tests/models/schema_tests/window_function_test.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql, macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql, macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql, macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql, macros/schema_tests/table_shape/expect_column_to_exist.sql, macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql, macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql, macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql, macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql, macros/schema_tests/table_shape/expect_table_columns_to_not_contain_set.sql
Fixes #230 
This PR makes calls to `type_*` macros fully qualified, e.g. `dbt_expectations.type_timestamp()` and `dbt.type_string()` to avoid namespace collisions with legacy macros in dbt_utils.
cc: @Maayan-s @elongl
=> Make type macro calls fully qualified

README.md, integration_tests/models/schema_tests/schema.yml, macros/regex/regexp_instr.sql, macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql, macros/schema_tests/string_matching/expect_column_values_to_match_regex_list.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_regex.sql, macros/schema_tests/string_matching/expect_column_values_to_not_match_regex_list.sql
Closes #245 
I chose to validate the flag against the lists in the documentation for Postgres, Snowflake, and Redshift. I decided to raise an error if flags are passed to BQ (since they are not supported) or the "default" implementation (unclear support). 
One alternative to raising on all flags for those adapters would be to specifically check for the `i` flag and lowercase the column before passing it to regexp_instr.
=> Add optional flags argument to regex tests

macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql
I have column names with apostrophes (unfortunately).
Adding this escaper makes stuff work.
=> escape quotes in expect_column_values_to_be_in_type_list.sql

integration_tests/models/schema_tests/schema.yml, macros/regex/regexp_instr.sql
Fix regex match succeeding for any pattern in Postgres (#249)
Add expected-to-fail tests for regex (#207)
Coalesce array_length and 0 to avoid null in expression when no match exists resulting in always falsy `WHERE` condition on error check in tests.
- OS: Manjaro Linux 22.0.2
- Python: 3.10.9
- dbt: 1.4.5
- dbt-expectations: 0.8.3
- PostgreSQL: 14.6
=> Fix postgres__regexp_instr not validating regex #249

integration_tests/models/schema_tests/schema.yml, macros/regex/regexp_instr.sql
Add support for regex flags for BigQuery (#252)
Inline flags in non-capturing block 
- OS: Manjaro Linux 22.0.2
- Python: 3.10.9
- dbt: 1.4.5
- dbt-expectations: 0.8.3
- dbt-bigquery: 1.4.3
=> Add support for regex flags for BigQuery

macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
Closes #257 
Just adds a `count(*) as n_records` to expect_compound_columns_to_be_unique
Consistency between dbt-expectations and dbt-core uniqueness tests.  
@clausherther
=> #257 Add count to expect_compound_columns_to_be_unique

.circleci/config.yml, integration_tests/ci/profiles.yml, integration_tests/models/schema_tests/timeseries_hourly.sql, macros/math/rand.sql, macros/regex/regexp_instr.sql, macros/utils/datatypes.sql, packages.yml
This PR adds support for duckdb, including updates to integration tests and CI.
dbt-date recently added support for duckdb in conjunction with dbt metrics layer testing.  
@jwills
=> Add duckdb support

.circleci/config.yml, .gitignore, integration_tests/ci/profiles.yml, integration_tests/docker-compose.yml, integration_tests/docker-start.sh, integration_tests/docker-stop.sh, integration_tests/docker/hive-site.xml, integration_tests/docker/spark-defaults.conf, integration_tests/models/schema_tests/schema.yml, macros/math/log_natural.sql, macros/math/percentile_cont.sql, macros/regex/regexp_instr.sql, macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql, macros/utils/datatypes.sql, packages.yml
Closes #280 
This PR updates test macros and supporting integration tests, as well as CircleCI configs to support apache-spark.
Also updates dependency on `dbt-date` to latest version (`0.9.x`)
Regex support is currently experimental in integration testing (and set to `warn` only), as support for raw regex strings in SparkSQL is unclear.
Shim packages like spark-utils do not implement support for dbt-expectations.
=> [Feature] Add spark support

packages.yml
This increases the version dependency upper range for dbt-date so that new minor releases are included automatically, making dependency management easier down the road.
@clausherther
=> Change dbt-date version dependency upper range

.circleci/config.yml, integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/multi-column/expect_multicolumn_sum_to_equal.sql
Closes #290 
Just wrapped `sum_total` in Sum() 
This will allow a column name or a literal number to be used.  
@clausherther
=> Fix sum_total in expect_multicolumn_sum_to_equal to accept column names

.circleci/config.yml, README.md, integration_tests/ci/profiles.yml, integration_tests/models/schema_tests/schema.yml, macros/regex/regexp_instr.sql, macros/schema_tests/aggregate_functions/expect_column_proportion_of_unique_values_to_be_between.sql, macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql, macros/utils/datatypes.sql
Closes #293 
- Added Trino support
- Fixed expect_select_column_values_to_be_unique_within_record macro
- Fixed timeseries_data_extended.row_value expect_column_distinct_count_ tests row_conditions
@clausherther
=> Add Trino Support

macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql, macros/utils/md5.sql
Adds support for `md5` on Trino which doesn't support varchars for md5.
=> Add Trino md5 macro

.github/pull_request_template.md, README.md
Closes #307
Fix a couple spellings.
Neither misspelling is a big deal, and easy to live without. "Nice to have" rather than "need to have".
@clausherther
=> "Expect" instead of "Except"

README.md, integration_tests/models/schema_tests/data_test.sql, integration_tests/models/schema_tests/schema.yml, macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql, macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql
If set, the test will check that the values are not only strictly increasing/decreasing, but the difference between subsequent values is exactly `step`.
Closes #315
Adds optional field `step` to tests `expect_column_values_to_be_{in,de}creasing`. If this value is set, it requires that the difference between subsequent values is exactly `step`. If it's not set, the behaviour of the test is the same as now (i.e., this isn't a breaking change).
The caveat is that it will only work for numeric columns. The test is literally `value_field - value_field_lag = step`.
I wrote this test for my own project. As I've written it already, I decided to sent this PR even without discussions. I'm able to do any changes required to get it merged. It's also OK if you don't think this is a good improvement to …
=> Adds optional `step` param to expect_column_values_to_be_{in,de}creasing
